### ISSUE TITLE
Some problems to the result.

### ISSUE THREAD

**Issue by likezjuisee** [pwlmaciejewski/basset#2]
[Error: You need to specify at least one argument]
[root@localhost locust]# basset -n 10 http://www.so.com
FFFFFFFFFF
Average
  onLoad: 0.00 卤 NaN ms
  requests: 0 (html: 0, css: 0, js: 0, img: 0, other: 0)
[root@localhost locust]#

**Comment by pwlmc** [comment]
It looks like network connection issue
